jobs:
- name: u14nodall
  type: runSh
  steps:
    - TASK:
        runtime:
          options:
            imageName: "drydock/u14nodall"
            imageTag: master
        script:
        - grunt --version
        - mocha --version
        - vows --version
        - casperjs --version
        - bower --version
        - phantomjs --version
        - java -jar /srv/selenium-server-standalone-3.12.0.jar --version
        - nodejs --version
        - nvm list
